spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: book
          uri: http://localhost:8081
          predicates:
            - Path=/book/**
        - id: delivery
          uri: http://localhost:8081
          predicates:
            - Path=/delivery/**
        - id: rental
          uri: http://localhost:8082
          predicates:
            - Path=/rental/**

---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: book
          uri: http://localhost:8080
          predicates:
            - Path=/book/**
        - id: delivery
          uri: http://localhost:8080
          predicates:
            - Path=/delivery/**
        - id: rental
          uri: http://localhost:8080
          predicates:
            - Path=/rental/**